const icons = {
  MIC: 'fas fa-microphone',
  MIC_DISABLED: 'fas fa-microphone-slash',
  VIDEO: 'fas fa-video',
  VIDEO_DISABLED: 'fas fa-video-slash',
  CLOSE: 'fas fa-times',
  SPINNER: 'fas fa-spinner fa-spin',
  TV: 'fas fa-tv',
  CHECKMARK: 'fa fa-check',
  HAND_RAISE: 'far fa-hand-paper',
  LAPTOP: 'fas fa-laptop',
  BROADCAST: 'fas fa-broadcast-tower',
  VOLUME_ON: 'fas fa-volume-up',
  VOLUME_OFF: 'fas fa-volume-mute',
  PHONE: 'fas fa-phone',
  ADD: 'fa fa-plus',
  TRASH: 'far fa-trash-alt',
  CROWN: 'fas fa-crown',
  ERROR: 'fas fa-exclamation-triangle',
  SUCCESS: 'fas fa-check-circle',
  INFO: 'fas fa-info-circle',
  HELP: 'fas fa-question-circle',
};

export default icons;
